/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/openOffice.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh
          geometry={nodes.Material2003.geometry}
          material={nodes.Material2003.material}
          material-color="#2E2E2E"
        />
        <mesh
          geometry={nodes.Material2004.geometry}
          material={nodes.Material2004.material}
        />
        <mesh
          geometry={nodes.Material2.geometry}
          material={materials.Color_000}
          material-color="pink"
        />
        <mesh
          geometry={nodes.Material2001.geometry}
          material={nodes.Material2001.material}
          material-color="#FF5E18"
        />
        <mesh
          geometry={nodes.Material2002.geometry}
          material={nodes.Material2002.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/openOffice.glb");
